import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { AuthProvider } from "@/context/auth-context";
import { validateSession } from "@/lib/auth/session-server";

// ... existing imports

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateSession();
  let user = null;

  if (session) {
    // Optimistically assume the session is valid and use the ID to fetch full details
    // Ideally we might want to optimize this to not require a second DB call if possible,
    // but for now this ensures we have the correct email/name which aren't in the token payload.
    const { prisma } = await import("@repo/database");
    const dbUser = await prisma.user.findUnique({
      where: { id: session.sub },
      select: { id: true, email: true, name: true, role: true }
    });
    
    if (dbUser) {
      user = { 
        id: dbUser.id, 
        email: dbUser.email, 
        name: dbUser.name || undefined, 
        role: dbUser.role 
      };
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>{children}</AuthProvider>
      </body>
    </html>
  );
}

